name: Workflow

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply-changes:
    name: Apply ${{ matrix.stack }}

    runs-on: ubuntu-latest

    concurrency: pulumi

    strategy:
      fail-fast: false
      matrix:
        include:
          - stack: prod
            refresh: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detecting changes in ${{ matrix.stack }}
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'stacks/${{ matrix.path }}/**'
              - 'yarn.lock'
              - 'package.json'
              - '.github/workflows/*'
              - 'Pulumi.${{ matrix.stack }}.yaml'

      - name: Authenticate to GCP
        if: github.event_name == 'workflow_dispatch' OR steps.changes.outputs.src == 'true'
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: kubernetes-eng@ayr-core-service.iam.gserviceaccount.com

      - name: Use Node LTS
        if: github.event_name == 'workflow_dispatch' OR steps.changes.outputs.src == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn

      - name: Install dependencies
        if: github.event_name == 'workflow_dispatch' OR steps.changes.outputs.src == 'true'
        run: yarn install

      - name: Lint
        if: github.event_name == 'workflow_dispatch' OR steps.changes.outputs.src == 'true'
        run: yarn lint

      - uses: pulumi/actions@v3
        if: github.event_name == 'workflow_dispatch' OR steps.changes.outputs.src == 'true'
        with:
          command: up
          refresh: ${{ matrix.refresh }}
          stack-name: ${{ matrix.stack }}
